services:
  worker-1:
    build:
      context: .
    ports:
      - 3001:3001
    environment:
      WORKER_PORT: 3001
      RUST_LOG: info
      MAX_WORK_MILLISECONDS: 100
  worker-2:
    build:
      context: .
    ports:
      - 3002:3002
    environment:
      WORKER_PORT: 3002
      RUST_LOG: info
      MAX_WORK_MILLISECONDS: 1000
  worker-3:
    build:
      context: .
    ports:
      - 3003:3003
    environment:
      WORKER_PORT: 3003
      RUST_LOG: info
      MAX_WORK_MILLISECONDS: 2000
